name: Deploy Images to GHCR

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: nrmnqdds
          password: ${{secrets.GHCR_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/nrmnqdds/imaluum-backend:${{ github.ref }}
          docker push ghcr.io/nrmnqdds/imaluum-backend:${{ github.ref }}